third_party/filebrowser/urls.py
from django.conf.urls import *

urlpatterns = patterns('',
    
    # filebrowser urls
    url(r'^browse/$', 'filebrowser.views.browse', name="fb_browse"),
    url(r'^mkdir/', 'filebrowser.views.mkdir', name="fb_mkdir"),
    url(r'^upload/', 'filebrowser.views.upload', name="fb_upload"),
    url(r'^rename/$', 'filebrowser.views.rename', name="fb_rename"),
    url(r'^delete/$', 'filebrowser.views.delete', name="fb_delete"),
    url(r'^versions/$', 'filebrowser.views.versions', name="fb_versions"),
    
    url(r'^check_file/$', 'filebrowser.views._check_file', name="fb_check"),
    url(r'^upload_file/$', 'filebrowser.views._upload_file', name="fb_do_upload"),
    
)

webapp/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns(
    'webapp.views',
    url(r'^$', 'view_home'),
)

urlpatterns += patterns(
    '',
    url(r'^front-edit/', include('front.urls')),
)

urlpatterns += patterns(
    '',
    url(r'^admin/filebrowser/', include('filebrowser.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEVELOPMENT:
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

urlpatterns += patterns(
    'categories.views',
    url(r'^edit/category-item/(?P<a_id>.*)$', 'edit_category_item'),
    url(r'^category/(?P<a_slug>.*)/(?P<b_slug>.*)$', 'view_category_item'),
    url(r'^category/(?P<a_slug>.*)$', 'view_category'),
)

urlpatterns += patterns(
    'page_content.views',
    url(r'^edit/(?P<a_slug>.*)$', 'edit_web_page'),
    url(r'^(?P<a_slug>.*)$', 'view_web_page'),
)

third_party/filebrowser/models.py
# This file is only necessary for the tests to work

third_party/filebrowser/forms.py
# coding: utf-8

# imports
import re, os

# django imports
from django import forms
from django.forms.formsets import BaseFormSet
from django.utils.translation import ugettext as _

# filebrowser imports
from filebrowser.settings import MAX_UPLOAD_SIZE, FOLDER_REGEX
from filebrowser.functions import convert_filename

alnum_name_re = re.compile(FOLDER_REGEX)

class MakeDirForm(forms.Form):
    """
    Form for creating Folder.
    """
    
    def __init__(self, path, *args, **kwargs):
        self.path = path
        super(MakeDirForm, self).__init__(*args, **kwargs)
        
    dir_name = forms.CharField(widget=forms.TextInput(attrs=dict({ 'class': 'vTextField' }, max_length=50, min_length=3)), label=_(u'Name'), help_text=_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'), required=True)
    
    def clean_dir_name(self):
        if self.cleaned_data['dir_name']:
            # only letters, numbers, underscores, spaces and hyphens are allowed.
            if not alnum_name_re.search(self.cleaned_data['dir_name']):
                raise forms.ValidationError(_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'))
            # Folder must not already exist.
            if os.path.isdir(os.path.join(self.path, convert_filename(self.cleaned_data['dir_name']))):
                raise forms.ValidationError(_(u'The Folder already exists.'))
        return convert_filename(self.cleaned_data['dir_name'])


class RenameForm(forms.Form):
    """
    Form for renaming Folder/File.
    """
    
    def __init__(self, path, file_extension, *args, **kwargs):
        self.path = path
        self.file_extension = file_extension
        super(RenameForm, self).__init__(*args, **kwargs)
    
    name = forms.CharField(widget=forms.TextInput(attrs=dict({ 'class': 'vTextField' }, max_length=50, min_length=3)), label=_(u'New Name'), help_text=_('Only letters, numbers, underscores, spaces and hyphens are allowed.'), required=True)
    
    def clean_name(self):
        if self.cleaned_data['name']:
            # only letters, numbers, underscores, spaces and hyphens are allowed.
            if not alnum_name_re.search(self.cleaned_data['name']):
                raise forms.ValidationError(_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'))
            #  folder/file must not already exist.
            if os.path.isdir(os.path.join(self.path, convert_filename(self.cleaned_data['name']))):
                raise forms.ValidationError(_(u'The Folder already exists.'))
            elif os.path.isfile(os.path.join(self.path, convert_filename(self.cleaned_data['name']) + self.file_extension)):
                raise forms.ValidationError(_(u'The File already exists.'))
        return convert_filename(self.cleaned_data['name'])

third_party/filebrowser/views.py
# coding: utf-8

# general imports
from time import gmtime, strftime

import os
import re


# django imports
from django.shortcuts import render_to_response, HttpResponse
from django.template import RequestContext as Context
from django.http import HttpResponseRedirect, Http404
from django.contrib.admin.views.decorators import staff_member_required
from django.views.decorators.cache import never_cache
from django.utils.translation import ugettext as _
from django.conf import settings
from django import forms
from django.core.urlresolvers import reverse
from django.core.exceptions import ImproperlyConfigured
from django.dispatch import Signal
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.utils.encoding import smart_str

try:
	# django SVN
	from django.views.decorators.csrf import csrf_exempt
except:
	# django 1.1
	from django.contrib.csrf.middleware import csrf_exempt

from django.contrib import messages

# filebrowser imports
from filebrowser.settings import *
from filebrowser.conf import fb_settings
from filebrowser.functions import path_to_url, sort_by_attr, get_path, get_file, get_version_path, get_breadcrumbs, \
	get_filterdate, get_settings_var, handle_file_upload, convert_filename
from filebrowser.templatetags.fb_tags import query_helper
from filebrowser.base import FileObject
from filebrowser.decorators import flash_login_required

# Precompile regular expressions
filter_re = []
for exp in EXCLUDE:
	filter_re.append(re.compile(exp))
for k, v in VERSIONS.iteritems():
	exp = (r'_%s.(%s)') % (k, '|'.join(EXTENSION_LIST))
	filter_re.append(re.compile(exp))


def _check_access(request, *path):
	"""
	Return absolute file path if access allow or raise exception.
	"""
	abs_path = os.path.abspath(os.path.join(
		fb_settings.MEDIA_ROOT, fb_settings.DIRECTORY, *path))
	if not abs_path.startswith(os.path.abspath(os.path.join(
			fb_settings.MEDIA_ROOT, fb_settings.DIRECTORY))):
		# cause any attempt to leave media root directory to fail
		raise Http404
	return abs_path


def _template():
	if fb_settings.SUIT_TEMPLATE:
		path = 'suit/'
	else:
		path = 'filebrowser/'

	return path


def browse(request):
	"""
	Browse Files/Directories.
	"""
	# QUERY / PATH CHECK
	query = request.GET.copy()
	path = get_path(query.get('dir', ''))
	directory = get_path('')

	if 'pop' in query:
		is_popup = True
	else:
		is_popup = False

	if path is not None:
		abs_path = _check_access(request, path)

	if path is None:
		msg = _('The requested Folder does not exist.')
		messages.warning(request, message=msg)
		if directory is None:
			# The DIRECTORY does not exist, raise an error to prevent eternal redirecting.
			raise ImproperlyConfigured, _("Error finding Upload-Folder. Maybe it does not exist?")
		redirect_url = reverse("fb_browse") + query_helper(query, "", "dir")
		return HttpResponseRedirect(redirect_url)

	# INITIAL VARIABLES
	results_var = {'results_total': 0, 'results_current': 0, 'delete_total': 0, 'images_total': 0, 'select_total': 0}
	counter = {}
	for k, v in EXTENSIONS.iteritems():
		counter[k] = 0

	dir_list = os.listdir(abs_path)
	files = []
	for file in dir_list:

		# EXCLUDE FILES MATCHING VERSIONS_PREFIX OR ANY OF THE EXCLUDE PATTERNS
		filtered = file.startswith('.')
		for re_prefix in filter_re:
			if re_prefix.search(file):
				filtered = True
		if filtered:
			continue
		results_var['results_total'] += 1

		# CREATE FILEOBJECT
		fileobject = FileObject(os.path.join(fb_settings.DIRECTORY, path, file))

		# FILTER / SEARCH
		append = False
		if fileobject.filetype == request.GET.get('filter_type', fileobject.filetype) and get_filterdate(
				request.GET.get('filter_date', ''), fileobject.date):
			append = True
		if request.GET.get('q') and not re.compile(request.GET.get('q').lower(), re.M).search(file.lower()):
			append = False

		# APPEND FILE_LIST
		if append:
			_type = query.get('type')
			try:
				# COUNTER/RESULTS
				if fileobject.filetype == 'Image':
					results_var['images_total'] += 1
				if fileobject.filetype != 'Folder':
					results_var['delete_total'] += 1
				elif fileobject.filetype == 'Folder' and fileobject.is_empty:
					results_var['delete_total'] += 1
				if _type and _type in SELECT_FORMATS and fileobject.filetype in SELECT_FORMATS[_type]:
					results_var['select_total'] += 1
				elif not _type:
					results_var['select_total'] += 1
			except OSError:
				# Ignore items that have problems
				continue
			else:
				files.append(fileobject)
				results_var['results_current'] += 1

		# COUNTER/RESULTS
		if fileobject.filetype:
			counter[fileobject.filetype] += 1

	# SORTING
	query['o'] = request.GET.get('o', DEFAULT_SORTING_BY)
	query['ot'] = request.GET.get('ot', DEFAULT_SORTING_ORDER)
	files = sort_by_attr(files, request.GET.get('o', DEFAULT_SORTING_BY))
	if not request.GET.get('ot') and DEFAULT_SORTING_ORDER == "desc" or request.GET.get('ot') == "desc":
		files.reverse()

	p = Paginator(files, LIST_PER_PAGE)
	try:
		page_nr = request.GET.get('p', '1')
	except:
		page_nr = 1
	try:
		page = p.page(page_nr)
	except (EmptyPage, InvalidPage):
		page = p.page(p.num_pages)

	template = _template() + 'index.html'

	context = {
	'dir': path,
	'p': p,
	'page': page,
	'results_var': results_var,
	'counter': counter,
	'query': query,
	'title': _(u'FileBrowser'),
	'settings_var': get_settings_var(),
	'breadcrumbs': get_breadcrumbs(query, path),
	'breadcrumbs_title': "",
	'is_popup': is_popup
	}

	return render_to_response(template, context, context_instance=Context(request))


browse = staff_member_required(never_cache(browse))


# mkdir signals
filebrowser_pre_createdir = Signal(providing_args=["path", "dirname"])
filebrowser_post_createdir = Signal(providing_args=["path", "dirname"])


def mkdir(request):
	"""
	Make Directory.
	"""

	from filebrowser.forms import MakeDirForm

	# QUERY / PATH CHECK
	query = request.GET
	path = get_path(query.get('dir', ''))

	if 'pop' in query:
		is_popup = True
	else:
		is_popup = False

	if path is None:
		msg = _('The requested Folder does not exist.')
		messages.warning(request, message=msg)
		return HttpResponseRedirect(reverse("fb_browse"))
	abs_path = _check_access(request, path)

	if request.method == 'POST':
		form = MakeDirForm(abs_path, request.POST)
		if form.is_valid():
			_new_dir_name = form.cleaned_data['dir_name']
			server_path = _check_access(request, path, _new_dir_name)
			try:
				# PRE CREATE SIGNAL
				filebrowser_pre_createdir.send(sender=request, path=path, dirname=_new_dir_name)
				# CREATE FOLDER
				os.mkdir(server_path)
				os.chmod(server_path, 0775)
				# POST CREATE SIGNAL
				filebrowser_post_createdir.send(sender=request, path=path, dirname=_new_dir_name)
				# MESSAGE & REDIRECT
				msg = _('The Folder %s was successfully created.') % (_new_dir_name)
				messages.success(request, message=msg)
				# on redirect, sort by date desc to see the new directory on top of the list
				# remove filter in order to actually _see_ the new folder
				# remove pagination
				redirect_url = reverse("fb_browse") + query_helper(query, "ot=desc,o=date",
				                                                   "ot,o,filter_type,filter_date,q,p")
				return HttpResponseRedirect(redirect_url)
			except OSError, (errno, strerror):
				if errno == 13:
					form.errors['dir_name'] = forms.util.ErrorList([_('Permission denied.')])
				else:
					form.errors['dir_name'] = forms.util.ErrorList([_('Error creating folder.')])
	else:
		form = MakeDirForm(abs_path)

	return render_to_response(_template() + 'makedir.html', {
		'form': form,
		'query': query,
		'title': _(u'New Folder'),
		'settings_var': get_settings_var(),
		'breadcrumbs': get_breadcrumbs(query, path),
		'breadcrumbs_title': _(u'New Folder'),
		'is_popup': is_popup
	}, context_instance=Context(request))


mkdir = staff_member_required(never_cache(mkdir))


def upload(request):
	"""
	Multipe File Upload.
	"""

	from django.http import parse_cookie

	# QUERY / PATH CHECK
	query = request.GET
	path = get_path(query.get('dir', ''))

	if 'pop' in query:
		is_popup = True
	else:
		is_popup = False

	if path is None:
		msg = _('The requested Folder does not exist.')
		messages.warning(request, message=msg)
		return HttpResponseRedirect(reverse("fb_browse"))
	abs_path = _check_access(request, path)

	# SESSION (used for flash-uploading)
	session_key = request.COOKIES.get(settings.SESSION_COOKIE_NAME, None)

	return render_to_response(_template() + 'upload.html', {
		'query': query,
		'title': _(u'Select files to upload'),
		'settings_var': get_settings_var(),
		'session_key': session_key,
		'breadcrumbs': get_breadcrumbs(query, path),
		'breadcrumbs_title': _(u'Upload'),
		'is_popup': is_popup
	}, context_instance=Context(request))


upload = staff_member_required(never_cache(upload))


@csrf_exempt
@staff_member_required
def _check_file(request):
	"""
	Check if file already exists on the server.
	"""

	import json

	folder = request.POST.get('folder')
	fb_uploadurl_re = re.compile(r'^.*(%s)' % reverse("fb_upload"))
	folder = fb_uploadurl_re.sub('', folder)

	fileArray = {}
	if request.method == 'POST':
		for k, v in request.POST.items():
			if k != "folder":
				v = convert_filename(v)
				if os.path.isfile(smart_str(_check_access(request, folder, v))):
					fileArray[k] = v

	return HttpResponse(json.dumps(fileArray))


# upload signals
filebrowser_pre_upload = Signal(providing_args=["path", "file"])
filebrowser_post_upload = Signal(providing_args=["path", "file"])


@csrf_exempt
@flash_login_required
@staff_member_required
def _upload_file(request):
	"""
	Upload file to the server.
	"""

	from django.core.files.move import file_move_safe

	if request.method == 'POST':
		folder = request.POST.get('folder')
		fb_uploadurl_re = re.compile(r'^.*(%s)' % reverse("fb_upload"))
		folder = fb_uploadurl_re.sub('', folder)
		abs_path = _check_access(request, folder)
		if request.FILES:
			filedata = request.FILES['Filedata']
			filedata.name = convert_filename(filedata.name)

third_party/filebrowser/templates/suit/custom_field.html
{% load fb_versions %}
<input id="{{ final_attrs.id }}" type="text" class="vFileBrowseField" name="{{ final_attrs.name }}" value="{{ value }}" /><a href="javascript:FileBrowser.show('{{ final_attrs.id }}', '{% url "fb_browse" %}?pop=1{% if final_attrs.directory %}&amp;dir={{ final_attrs.directory }}{% endif %}{% if final_attrs.format %}&amp;type={{ final_attrs.format }}{% endif %}');" class="btn btn-info" style="margin-left: 10px; margin-right: 10px;">
    <i class="icon-white icon-search"></i>
</a>
{% ifequal value.filetype "Image" %}
<p class="help" id="help_{{ final_attrs.id }}">
    <a href="{{ value.url_full }}" target="_blank" id="link_{{ final_attrs.id }}">
        <img id="image_{{ final_attrs.id }}" src="{% version value.path final_attrs.ADMIN_THUMBNAIL %}" class="preview" />
    </a>
</p>
{% else %}
<p class="help" id="help_{{ final_attrs.id }}" style="display: none;">
    <a href="javascript://" target="_self" id="link_{{ final_attrs.id }}">
        <img id="image_{{ final_attrs.id }}" class="preview" src="" />
    </a>
</p>
{% endifequal %}
{% if final_attrs.DEBUG %}
<p>
    <strong>Path</strong> {{ value.path }}<br />
    <strong>FileType</strong> {{ value.filetype }}<br /><br />
    <strong>Directory</strong> {{ final_attrs.directory }}<br />
    <strong>Extensions</strong> {{ final_attrs.extensions }}<br />
    <strong>Format</strong> {{ final_attrs.format }}
</p>
{% endif %}

third_party/filebrowser/templates/suit/makedir.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static admin_list admin_urls %}
{% load fb_tags fb_csrf %}
{% load url from future %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/suit-filebrowser.css" />
{% endblock %}

{% block breadcrumbs %}
    {% include "suit/include/breadcrumbs.html" %}
{% endblock %}

{% block content %}
    <div id="content-main" class="inner-two-columns">
        <form action="{% query_string '' 'p' %}" method="post" class="form-horizontal">
            {% fb_csrf_token %}
            <div class="inner-right-column">
                <div class="box save-box">
                    <div class="submit-row clearfix">
                        <input type="submit" value="{% trans 'Submit' %}" class="btn btn-high btn-info" />
                    </div>
                </div>
            </div>
            <div class="inner-center-column">
                <div class="tab-content tab-content-main">
                    {% if form.errors %}
                        <div class="alert alert-error">
                            <strong>{% trans 'Please correct the following errors.' %}</strong>
                        </div>
                    {% endif %}
                    <fieldset class="module aligned">
                        <div class="control-group">
                            <div class="control-label">
                                <label class="required" for="id_dir_name">{{ form.dir_name.label }}</label>
                            </div>
                            <div class="controls">
                                {{ form.dir_name }}
                                {% if form.dir_name.errors %}<span class="help-inline">{{ form.dir_name.errors }}</span>{% endif %}
                                <span class="help-block">
                                    {{ form.dir_name.help_text|safe }}
                                    {% if settings_var.CONVERT_FILENAME %}<br />{% trans "The Name will be converted to lowercase. Spaces will be replaced with underscores." %}{% endif %}
                                </span>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

third_party/filebrowser/templates/suit/rename.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static admin_list admin_urls %}
{% load fb_tags fb_csrf %}
{% load url from future %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/suit-filebrowser.css" />
{% endblock %}

{% block coltype %}colM{% endblock %}

{% block bodyclass %}change-form{% endblock %}

{% block breadcrumbs %}
    {% include "suit/include/breadcrumbs.html" %}
{% endblock %}

{% block content %}
    <div id="content-main" class="inner-two-columns">
        <form action="{% query_string "" "filter_date,filter_type,q,p" %}" method="post" class="form-horizontal">
            {% fb_csrf_token %}
            <div class="inner-right-column">
                <div class="box save-box">
                    <div class="submit-row clearfix">
                        <input type="submit" value="{% trans 'Submit' %}" class="btn btn-high btn-info" />
                    </div>
                </div>
            </div>
            <div class="inner-center-column">
                <div class="tab-content tab-content-main">
                    {% if form.errors %}
                        <div class="alert alert-error">
                            <strong>{% trans 'Please correct the following errors.' %}</strong>
                        </div>
                    {% endif %}
                    <fieldset class="module aligned">
                        <div class="control-group">
                            <div class="control-label">
                                <label class="required" for="id_dir_name">{{ form.name.label }}</label>
                            </div>
                            <div class="controls">
                                {{ form.name }}{% if file_extension %}<b>{{ file_extension }}</b>{% endif %}
                                {% if form.name.errors %}<span class="help-inline">{{ form.name.errors }}</span>{% endif %}
                                <span class="help-block">
                                    {{ form.name.help_text|safe }}

                                </span>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

third_party/filebrowser/templates/suit/upload.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static admin_list admin_urls %}
{% load fb_tags %}
{% load url from future %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/uploadify.css" />
    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/suit-filebrowser.css" />
{% endblock %}

{% block extrahead %}
    {{ block.super }}
    <script type="text/javascript" src="../../jsi18n/"></script>
    <script type="text/javascript" src="{% static "admin/js/core.js" %}"></script>

    <script type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/jquery-1.3.2.min.js"></script>
    <script type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/jquery.uploadify.v2.1.0.js"></script>
    <script type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/swfobject.js"></script>

    <script type="text/javascript">
        (function($){
            $(document).ready(function() {
                $('#id_file').uploadify({
                    'uploader'          : '{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/uploadify.swf',
                    'script'            : '{% url "fb_do_upload" %}',
                    'scriptData'        : {'session_key': '{{session_key}}'},
                    'checkScript'       : '{% url "fb_check" %}',
                    'cancelImg'         : '{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/cancel.png',
                    'auto'              : false,
                    'folder'            : '{{ query.dir }}',
                    'multi'             : true,
                    'fileDesc'          : '{% for extension in settings_var.EXTENSIONS.items %}{% ifnotequal extension.0 'Folder' %}{% for item in extension.1 %}*{{ item|safe }};{% endfor %}{% endifnotequal %}{% endfor %}',
                    'fileExt'           : '{% for extension in settings_var.EXTENSIONS.items %}{% ifnotequal extension.0 'Folder' %}{% for item in extension.1 %}*{{ item|safe }};{% endfor %}{% endifnotequal %}{% endfor %}',
                    'sizeLimit'         : {{ settings_var.MAX_UPLOAD_SIZE }},
                    'scriptAccess'      : 'sameDomain',
                    'queueSizeLimit'    : 50,
                    'simUploadLimit'    : 1,
                    'width'             : 300,
                    'height'            : 30,
                    'hideButton'        : false,
                    'wmode'             : 'transparent',
                    'onAllComplete'     : function(){var newpath='../browse/{% query_string %}';window.location=newpath;},
                    translations        : {
                        browseButton: '{% trans "BROWSE" %}',
                        error: '{% trans "An Error occured" %}',
                        completed: '{% trans "Completed" %}',
                        replaceFile: '{% trans "Do you want to replace the file" %}',
                        unitKb: '{% trans "KB" %}',
                        unitMb: '{% trans "MB" %}'
                    }
                });
                $('input:submit').click(function(evt){
                    $('#id_file').uploadifyUpload();
                    return false;
                });
                $('input[name="clear"]').click(function(evt){
                    $('#id_file').uploadifyClearQueue();
                    return false;
                });
            });
        })(jQuery.noConflict());
    </script>
{% endblock %}

{% block coltype %}colM{% endblock %}

{% block bodyclass %}change-form{% endblock %}

{% block breadcrumbs %}
    {% include "suit/include/breadcrumbs.html" %}
{% endblock %}

{% block content %}
    <div id="content-main" class="inner-two-columns">
        <form class="form-horizontal">
            <div class="inner-right-column">
                <div class="box save-box">
                    <div class="submit-row clearfix">
                        <input type="submit" value="{% trans 'Submit' %}" class="btn btn-high btn-info" />
                        <input type="button" value="{% trans "Clear Queue" %}" class="btn btn-high btn-info" name="clear"/>
                    </div>
                </div>
            </div>
            <div class="inner-center-column">
                <div class="tab-content tab-content-main">
                    <fieldset class="module aligned">
                        <div class="control-group">
                            <div class="control-label">
                                <label class="required" for="id_file">{% trans "Select a file." %}</label>
                            </div>
                            <div class="controls">
                                <input type="File" id="id_file" class="btn btn-info"/>
                                {% for extension in settings_var.EXTENSIONS.items %}
                                <span class="help-block">

                                        {% ifnotequal extension.0 'Folder' %}
                                            <strong>{% if forloop.first %}{% trans "Allowed" %}:{% else %}&nbsp;{% endif %}</strong>
                                            <p>{{ extension.0|safe }} ({{ extension.1|join:", "|safe }})</p>
                                        {% endifnotequal %}

                                </span>
                                {% endfor %}
                                <br>
                                <span class="help-block">
                                    <strong>{% trans "Max. Filesize" %}:</strong>
                                    <p>{{ settings_var.MAX_UPLOAD_SIZE|filesizeformat }}</p>
                                </span>
                                {% if settings_var.CONVERT_FILENAME %}
                                    <br>
                                    <span class="help-block">
                                        <strong>{% trans "The Name will be converted to lowercase. Spaces will be replaced with underscores." %}</strong>
                                    </span>
                                {% endif %}
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
        </form>
    </div>
{% endblock %}