third_party/filebrowser/urls.py
from django.conf.urls import *

urlpatterns = patterns('',
    
    # filebrowser urls
    url(r'^browse/$', 'filebrowser.views.browse', name="fb_browse"),
    url(r'^mkdir/', 'filebrowser.views.mkdir', name="fb_mkdir"),
    url(r'^upload/', 'filebrowser.views.upload', name="fb_upload"),
    url(r'^rename/$', 'filebrowser.views.rename', name="fb_rename"),
    url(r'^delete/$', 'filebrowser.views.delete', name="fb_delete"),
    url(r'^versions/$', 'filebrowser.views.versions', name="fb_versions"),
    
    url(r'^check_file/$', 'filebrowser.views._check_file', name="fb_check"),
    url(r'^upload_file/$', 'filebrowser.views._upload_file', name="fb_do_upload"),
    
)

webapp/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns(
    'webapp.views',
    url(r'^$', 'view_home'),
)

urlpatterns += patterns(
    '',
    url(r'^front-edit/', include('front.urls')),
)

urlpatterns += patterns(
    '',
    url(r'^admin/filebrowser/', include('filebrowser.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEVELOPMENT:
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

urlpatterns += patterns(
    'categories.views',
    url(r'^edit/category-item/(?P<a_id>.*)$', 'edit_category_item'),
    url(r'^category/(?P<a_slug>.*)/(?P<b_slug>.*)$', 'view_category_item'),
    url(r'^category/(?P<a_slug>.*)$', 'view_category'),
)

urlpatterns += patterns(
    'page_content.views',
    url(r'^edit/(?P<a_slug>.*)$', 'edit_web_page'),
    url(r'^(?P<a_slug>.*)$', 'view_web_page'),
)

contact/models.py
from django.contrib.sites.models import Site
from django.db import models


class ContactLead(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    message = models.TextField(max_length=1000)

    date = models.DateField()

    def __unicode__(self):
        return self.first_name

    class Meta:
        verbose_name_plural = 'Contact Leads'
        verbose_name = 'Contact Lead'
        ordering = ('-date', 'first_name', 'last_name')


class ContactMap(models.Model):
    site = models.OneToOneField(Site)
    label = models.CharField(max_length=100, help_text='This is only used in the admin.')
    iframe = models.CharField(max_length=400, help_text='You can get this from Google Maps.')

    def __unicode__(self):
        return self.label

contact/forms.py
from django import forms
from contact.models import ContactLead


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactLead
        fields = ('first_name', 'last_name', 'email', 'message')

contact/views.py
import datetime
import logging
from django.conf import settings
from django.contrib.sites.models import Site
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.template.loader import render_to_string
from contact.forms import ContactForm
from contact.models import ContactLead, ContactMap
from utility import set_detail_context


def view_contact(request, page):
    message = False

    try:
        # GET MAP FOR CURRENT SITE
        current_site = Site.objects.get_current()
        contact_map = ContactMap.objects.get(site=current_site)

    except Exception, e:
        logging.error(e)
        contact_map = None

    if request.method == 'POST':
        contact_form = ContactForm(data=request.POST)

        if contact_form.is_valid():
            cleaned_data = contact_form.cleaned_data

            lead = ContactLead()
            lead.first_name = cleaned_data['first_name']
            lead.last_name = cleaned_data['last_name']
            lead.email = cleaned_data['email']
            lead.message = cleaned_data['message']
            lead.date = datetime.datetime.now()
            lead.save()

            # SEND EMAIL
            email_context = {'contactLead': lead}

            subject, from_email, to_email = 'New Contact Lead', settings.DEFAULT_FROM_EMAIL, [settings.ONLINE_CONTACT_EMAIL]
            text_content = render_to_string("email/contact/new_contact_lead_string.html", email_context)
            html_content = render_to_string("email/contact/new_contact_lead_html.html", email_context)
            msg = EmailMultiAlternatives(subject, text_content, from_email, to_email)
            msg.attach_alternative(html_content, "text/html")
            msg.send()

            message = True

    else:
        contact_form = ContactForm()

    context = {'page': page, 'map': contact_map, 'contact_form': contact_form, 'message': message}
    set_detail_context(request, context)

    template = 'overrides/contact.html'

    return render_to_response(template, context, context_instance=RequestContext(request))

templates/overrides/contact.html
{% extends 'detail_page.html' %}
{% load front_tags %}


{% block page-title %}
    {% if page.meta_title %}{{ page.meta_title }}{% else %}{{ page.label }}{% endif %}
{% endblock %}


{% block extra-head %}

    <link type='text/css' rel='stylesheet' href='/static/css/detail.css'>

    <script type='text/javascript' src="/static/js/jquery.watermark.min.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {

            $('#id_first_name').watermark('First Name');
            $('#id_last_name').watermark('Last Name');
            $('#id_email').watermark('Email');
            $('#id_message').watermark('Message');

        });

    </script>

    {% front_edit_scripts editor='ckeditor' %}

{% endblock %}


{% block template_override_content %}

    {% if map %}
        <div id='map-wrapper' class='container'>

            {% autoescape off %}
                {{ map.iframe }}
            {% endautoescape %}

            <div class='clear-both'></div>

        </div>
    {% endif %}

    <div id='contact-form-wrapper' class='container'>

        <div class='row'>

            <div id='contact-left-col' class='col-md-6'>

                {% front_edit 'contact-form-left-col' django_front_key page.id %}
                    <h2>This is a headline</h2>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                        laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
                        voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
                        cupidatat
                        non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                {% end_front_edit %}

            </div>

            <div id='contact-form' class='col-md-6'>

                {% if message %}

                    {% front_edit 'contact-form-message' django_front_key page.id %}<h2>Thank You Message</h2>{% end_front_edit %}

                {% else %}

                    <form method='POST'>

                        {% csrf_token %}

                        {{ contact_form.first_name }}

                        {{ contact_form.last_name }}

                        {{ contact_form.email }}

                        {{ contact_form.message }}

                        <input type='submit' class='btn' value='Send'>

                    </form>

                {% endif %}

            </div>

        </div>

    </div>

{% endblock %}


{% if active_user %}
    {% block user-actions %}

        <span class='left'>
            <a onclick='displayManageWindow("/admin/page_content/webpage/{{ page.id }}/")'>edit page</a>
        </span>

        <span class='left'>
            <a onclick='displayManageWindow("/admin/contact/contactmap/")'>edit map</a>
        </span>

    {% endblock %}
{% endif %}